/*
 * ITU courses
 *
 * This service makes ITU courses even better
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Teacher struct {

	Id int32 `json:"id"`

	Name string `json:"name"`

	StudentPopularityScore int32 `json:"studentPopularityScore,omitempty"`
}
