/*
 * ITU courses
 *
 * This service makes ITU courses even better
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/v1/",
		Index,
	},

	Route{
		"CourseCourseIdDelete",
		strings.ToUpper("Delete"),
		"/v1/course/{courseId}",
		CourseCourseIdDelete,
	},

	Route{
		"CourseCourseIdGet",
		strings.ToUpper("Get"),
		"/v1/course/{courseId}",
		CourseCourseIdGet,
	},

	Route{
		"CourseCourseIdPost",
		strings.ToUpper("Post"),
		"/v1/course/{courseId}",
		CourseCourseIdPost,
	},

	Route{
		"CourseGet",
		strings.ToUpper("Get"),
		"/v1/course",
		CourseGet,
	},

	Route{
		"CoursePost",
		strings.ToUpper("Post"),
		"/v1/course",
		CoursePost,
	},

	Route{
		"StudentGet",
		strings.ToUpper("Get"),
		"/v1/student",
		StudentGet,
	},

	Route{
		"StudentPost",
		strings.ToUpper("Post"),
		"/v1/student",
		StudentPost,
	},

	Route{
		"StudentStudentIdGet",
		strings.ToUpper("Get"),
		"/v1/student/{studentId}",
		StudentStudentIdGet,
	},

	Route{
		"StudentStudentIdPost",
		strings.ToUpper("Post"),
		"/v1/student/{studentId}",
		StudentStudentIdPost,
	},

	Route{
		"TeacherGet",
		strings.ToUpper("Get"),
		"/v1/teacher",
		TeacherGet,
	},

	Route{
		"TeacherPost",
		strings.ToUpper("Post"),
		"/v1/teacher",
		TeacherPost,
	},

	Route{
		"TeacherTeacherIdGet",
		strings.ToUpper("Get"),
		"/v1/teacher/{teacherId}",
		TeacherTeacherIdGet,
	},

	Route{
		"TeacherTeacherIdPost",
		strings.ToUpper("Post"),
		"/v1/teacher/{teacherId}",
		TeacherTeacherIdPost,
	},
}
