/*
 * ITU courses
 *
 * This service makes ITU courses even better
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Student struct {
	Id int32 `json:"id"`
	Name string `json:"name"`
	Workload int32 `json:"workload,omitempty"`
}
