// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protoAttempt

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GetCoursesClient is the client API for GetCourses service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetCoursesClient interface {
	GetCourseList(ctx context.Context, in *CourseId, opts ...grpc.CallOption) (*Courses, error)
}

type getCoursesClient struct {
	cc grpc.ClientConnInterface
}

func NewGetCoursesClient(cc grpc.ClientConnInterface) GetCoursesClient {
	return &getCoursesClient{cc}
}

func (c *getCoursesClient) GetCourseList(ctx context.Context, in *CourseId, opts ...grpc.CallOption) (*Courses, error) {
	out := new(Courses)
	err := c.cc.Invoke(ctx, "/tutorial.getCourses/GetCourseList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetCoursesServer is the server API for GetCourses service.
// All implementations must embed UnimplementedGetCoursesServer
// for forward compatibility
type GetCoursesServer interface {
	GetCourseList(context.Context, *CourseId) (*Courses, error)
	mustEmbedUnimplementedGetCoursesServer()
}

// UnimplementedGetCoursesServer must be embedded to have forward compatible implementations.
type UnimplementedGetCoursesServer struct {
}

func (UnimplementedGetCoursesServer) GetCourseList(context.Context, *CourseId) (*Courses, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCourseList not implemented")
}
func (UnimplementedGetCoursesServer) mustEmbedUnimplementedGetCoursesServer() {}

// UnsafeGetCoursesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetCoursesServer will
// result in compilation errors.
type UnsafeGetCoursesServer interface {
	mustEmbedUnimplementedGetCoursesServer()
}

func RegisterGetCoursesServer(s grpc.ServiceRegistrar, srv GetCoursesServer) {
	s.RegisterService(&GetCourses_ServiceDesc, srv)
}

func _GetCourses_GetCourseList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CourseId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetCoursesServer).GetCourseList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tutorial.getCourses/GetCourseList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetCoursesServer).GetCourseList(ctx, req.(*CourseId))
	}
	return interceptor(ctx, in, info, handler)
}

// GetCourses_ServiceDesc is the grpc.ServiceDesc for GetCourses service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetCourses_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tutorial.getCourses",
	HandlerType: (*GetCoursesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCourseList",
			Handler:    _GetCourses_GetCourseList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "course/course.proto",
}
